// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// APIKey is the predicate function for apikey builders.
type APIKey func(*sql.Selector)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// AccountGroup is the predicate function for accountgroup builders.
type AccountGroup func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// PromoCode is the predicate function for promocode builders.
type PromoCode func(*sql.Selector)

// PromoCodeUsage is the predicate function for promocodeusage builders.
type PromoCodeUsage func(*sql.Selector)

// Proxy is the predicate function for proxy builders.
type Proxy func(*sql.Selector)

// RedeemCode is the predicate function for redeemcode builders.
type RedeemCode func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// SoraAccount is the predicate function for soraaccount builders.
type SoraAccount func(*sql.Selector)

// SoraCacheFile is the predicate function for soracachefile builders.
type SoraCacheFile func(*sql.Selector)

// SoraTask is the predicate function for soratask builders.
type SoraTask func(*sql.Selector)

// SoraUsageStat is the predicate function for sorausagestat builders.
type SoraUsageStat func(*sql.Selector)

// UsageCleanupTask is the predicate function for usagecleanuptask builders.
type UsageCleanupTask func(*sql.Selector)

// UsageLog is the predicate function for usagelog builders.
type UsageLog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserAllowedGroup is the predicate function for userallowedgroup builders.
type UserAllowedGroup func(*sql.Selector)

// UserAttributeDefinition is the predicate function for userattributedefinition builders.
type UserAttributeDefinition func(*sql.Selector)

// UserAttributeValue is the predicate function for userattributevalue builders.
type UserAttributeValue func(*sql.Selector)

// UserSubscription is the predicate function for usersubscription builders.
type UserSubscription func(*sql.Selector)
