// Code generated by ent, DO NOT EDIT.

package soraaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldAccountID, v))
}

// AccessToken applies equality check predicate on the "access_token" field. It's identical to AccessTokenEQ.
func AccessToken(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldAccessToken, v))
}

// SessionToken applies equality check predicate on the "session_token" field. It's identical to SessionTokenEQ.
func SessionToken(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldSessionToken, v))
}

// RefreshToken applies equality check predicate on the "refresh_token" field. It's identical to RefreshTokenEQ.
func RefreshToken(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldRefreshToken, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldClientID, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldEmail, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldUsername, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldRemark, v))
}

// UseCount applies equality check predicate on the "use_count" field. It's identical to UseCountEQ.
func UseCount(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldUseCount, v))
}

// PlanType applies equality check predicate on the "plan_type" field. It's identical to PlanTypeEQ.
func PlanType(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldPlanType, v))
}

// PlanTitle applies equality check predicate on the "plan_title" field. It's identical to PlanTitleEQ.
func PlanTitle(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldPlanTitle, v))
}

// SubscriptionEnd applies equality check predicate on the "subscription_end" field. It's identical to SubscriptionEndEQ.
func SubscriptionEnd(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldSubscriptionEnd, v))
}

// SoraSupported applies equality check predicate on the "sora_supported" field. It's identical to SoraSupportedEQ.
func SoraSupported(v bool) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldSoraSupported, v))
}

// SoraInviteCode applies equality check predicate on the "sora_invite_code" field. It's identical to SoraInviteCodeEQ.
func SoraInviteCode(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldSoraInviteCode, v))
}

// SoraRedeemedCount applies equality check predicate on the "sora_redeemed_count" field. It's identical to SoraRedeemedCountEQ.
func SoraRedeemedCount(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldSoraRedeemedCount, v))
}

// SoraRemainingCount applies equality check predicate on the "sora_remaining_count" field. It's identical to SoraRemainingCountEQ.
func SoraRemainingCount(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldSoraRemainingCount, v))
}

// SoraTotalCount applies equality check predicate on the "sora_total_count" field. It's identical to SoraTotalCountEQ.
func SoraTotalCount(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldSoraTotalCount, v))
}

// SoraCooldownUntil applies equality check predicate on the "sora_cooldown_until" field. It's identical to SoraCooldownUntilEQ.
func SoraCooldownUntil(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldSoraCooldownUntil, v))
}

// CooledUntil applies equality check predicate on the "cooled_until" field. It's identical to CooledUntilEQ.
func CooledUntil(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldCooledUntil, v))
}

// ImageEnabled applies equality check predicate on the "image_enabled" field. It's identical to ImageEnabledEQ.
func ImageEnabled(v bool) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldImageEnabled, v))
}

// VideoEnabled applies equality check predicate on the "video_enabled" field. It's identical to VideoEnabledEQ.
func VideoEnabled(v bool) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldVideoEnabled, v))
}

// ImageConcurrency applies equality check predicate on the "image_concurrency" field. It's identical to ImageConcurrencyEQ.
func ImageConcurrency(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldImageConcurrency, v))
}

// VideoConcurrency applies equality check predicate on the "video_concurrency" field. It's identical to VideoConcurrencyEQ.
func VideoConcurrency(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldVideoConcurrency, v))
}

// IsExpired applies equality check predicate on the "is_expired" field. It's identical to IsExpiredEQ.
func IsExpired(v bool) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldIsExpired, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldAccountID, v))
}

// AccessTokenEQ applies the EQ predicate on the "access_token" field.
func AccessTokenEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldAccessToken, v))
}

// AccessTokenNEQ applies the NEQ predicate on the "access_token" field.
func AccessTokenNEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldAccessToken, v))
}

// AccessTokenIn applies the In predicate on the "access_token" field.
func AccessTokenIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldAccessToken, vs...))
}

// AccessTokenNotIn applies the NotIn predicate on the "access_token" field.
func AccessTokenNotIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldAccessToken, vs...))
}

// AccessTokenGT applies the GT predicate on the "access_token" field.
func AccessTokenGT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldAccessToken, v))
}

// AccessTokenGTE applies the GTE predicate on the "access_token" field.
func AccessTokenGTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldAccessToken, v))
}

// AccessTokenLT applies the LT predicate on the "access_token" field.
func AccessTokenLT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldAccessToken, v))
}

// AccessTokenLTE applies the LTE predicate on the "access_token" field.
func AccessTokenLTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldAccessToken, v))
}

// AccessTokenContains applies the Contains predicate on the "access_token" field.
func AccessTokenContains(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContains(FieldAccessToken, v))
}

// AccessTokenHasPrefix applies the HasPrefix predicate on the "access_token" field.
func AccessTokenHasPrefix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasPrefix(FieldAccessToken, v))
}

// AccessTokenHasSuffix applies the HasSuffix predicate on the "access_token" field.
func AccessTokenHasSuffix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasSuffix(FieldAccessToken, v))
}

// AccessTokenIsNil applies the IsNil predicate on the "access_token" field.
func AccessTokenIsNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIsNull(FieldAccessToken))
}

// AccessTokenNotNil applies the NotNil predicate on the "access_token" field.
func AccessTokenNotNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotNull(FieldAccessToken))
}

// AccessTokenEqualFold applies the EqualFold predicate on the "access_token" field.
func AccessTokenEqualFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEqualFold(FieldAccessToken, v))
}

// AccessTokenContainsFold applies the ContainsFold predicate on the "access_token" field.
func AccessTokenContainsFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContainsFold(FieldAccessToken, v))
}

// SessionTokenEQ applies the EQ predicate on the "session_token" field.
func SessionTokenEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldSessionToken, v))
}

// SessionTokenNEQ applies the NEQ predicate on the "session_token" field.
func SessionTokenNEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldSessionToken, v))
}

// SessionTokenIn applies the In predicate on the "session_token" field.
func SessionTokenIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldSessionToken, vs...))
}

// SessionTokenNotIn applies the NotIn predicate on the "session_token" field.
func SessionTokenNotIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldSessionToken, vs...))
}

// SessionTokenGT applies the GT predicate on the "session_token" field.
func SessionTokenGT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldSessionToken, v))
}

// SessionTokenGTE applies the GTE predicate on the "session_token" field.
func SessionTokenGTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldSessionToken, v))
}

// SessionTokenLT applies the LT predicate on the "session_token" field.
func SessionTokenLT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldSessionToken, v))
}

// SessionTokenLTE applies the LTE predicate on the "session_token" field.
func SessionTokenLTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldSessionToken, v))
}

// SessionTokenContains applies the Contains predicate on the "session_token" field.
func SessionTokenContains(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContains(FieldSessionToken, v))
}

// SessionTokenHasPrefix applies the HasPrefix predicate on the "session_token" field.
func SessionTokenHasPrefix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasPrefix(FieldSessionToken, v))
}

// SessionTokenHasSuffix applies the HasSuffix predicate on the "session_token" field.
func SessionTokenHasSuffix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasSuffix(FieldSessionToken, v))
}

// SessionTokenIsNil applies the IsNil predicate on the "session_token" field.
func SessionTokenIsNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIsNull(FieldSessionToken))
}

// SessionTokenNotNil applies the NotNil predicate on the "session_token" field.
func SessionTokenNotNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotNull(FieldSessionToken))
}

// SessionTokenEqualFold applies the EqualFold predicate on the "session_token" field.
func SessionTokenEqualFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEqualFold(FieldSessionToken, v))
}

// SessionTokenContainsFold applies the ContainsFold predicate on the "session_token" field.
func SessionTokenContainsFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContainsFold(FieldSessionToken, v))
}

// RefreshTokenEQ applies the EQ predicate on the "refresh_token" field.
func RefreshTokenEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldRefreshToken, v))
}

// RefreshTokenNEQ applies the NEQ predicate on the "refresh_token" field.
func RefreshTokenNEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldRefreshToken, v))
}

// RefreshTokenIn applies the In predicate on the "refresh_token" field.
func RefreshTokenIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldRefreshToken, vs...))
}

// RefreshTokenNotIn applies the NotIn predicate on the "refresh_token" field.
func RefreshTokenNotIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldRefreshToken, vs...))
}

// RefreshTokenGT applies the GT predicate on the "refresh_token" field.
func RefreshTokenGT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldRefreshToken, v))
}

// RefreshTokenGTE applies the GTE predicate on the "refresh_token" field.
func RefreshTokenGTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldRefreshToken, v))
}

// RefreshTokenLT applies the LT predicate on the "refresh_token" field.
func RefreshTokenLT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldRefreshToken, v))
}

// RefreshTokenLTE applies the LTE predicate on the "refresh_token" field.
func RefreshTokenLTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldRefreshToken, v))
}

// RefreshTokenContains applies the Contains predicate on the "refresh_token" field.
func RefreshTokenContains(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContains(FieldRefreshToken, v))
}

// RefreshTokenHasPrefix applies the HasPrefix predicate on the "refresh_token" field.
func RefreshTokenHasPrefix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasPrefix(FieldRefreshToken, v))
}

// RefreshTokenHasSuffix applies the HasSuffix predicate on the "refresh_token" field.
func RefreshTokenHasSuffix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasSuffix(FieldRefreshToken, v))
}

// RefreshTokenIsNil applies the IsNil predicate on the "refresh_token" field.
func RefreshTokenIsNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIsNull(FieldRefreshToken))
}

// RefreshTokenNotNil applies the NotNil predicate on the "refresh_token" field.
func RefreshTokenNotNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotNull(FieldRefreshToken))
}

// RefreshTokenEqualFold applies the EqualFold predicate on the "refresh_token" field.
func RefreshTokenEqualFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEqualFold(FieldRefreshToken, v))
}

// RefreshTokenContainsFold applies the ContainsFold predicate on the "refresh_token" field.
func RefreshTokenContainsFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContainsFold(FieldRefreshToken, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDIsNil applies the IsNil predicate on the "client_id" field.
func ClientIDIsNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIsNull(FieldClientID))
}

// ClientIDNotNil applies the NotNil predicate on the "client_id" field.
func ClientIDNotNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotNull(FieldClientID))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContainsFold(FieldClientID, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContainsFold(FieldEmail, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameIsNil applies the IsNil predicate on the "username" field.
func UsernameIsNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIsNull(FieldUsername))
}

// UsernameNotNil applies the NotNil predicate on the "username" field.
func UsernameNotNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotNull(FieldUsername))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContainsFold(FieldUsername, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContainsFold(FieldRemark, v))
}

// UseCountEQ applies the EQ predicate on the "use_count" field.
func UseCountEQ(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldUseCount, v))
}

// UseCountNEQ applies the NEQ predicate on the "use_count" field.
func UseCountNEQ(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldUseCount, v))
}

// UseCountIn applies the In predicate on the "use_count" field.
func UseCountIn(vs ...int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldUseCount, vs...))
}

// UseCountNotIn applies the NotIn predicate on the "use_count" field.
func UseCountNotIn(vs ...int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldUseCount, vs...))
}

// UseCountGT applies the GT predicate on the "use_count" field.
func UseCountGT(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldUseCount, v))
}

// UseCountGTE applies the GTE predicate on the "use_count" field.
func UseCountGTE(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldUseCount, v))
}

// UseCountLT applies the LT predicate on the "use_count" field.
func UseCountLT(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldUseCount, v))
}

// UseCountLTE applies the LTE predicate on the "use_count" field.
func UseCountLTE(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldUseCount, v))
}

// PlanTypeEQ applies the EQ predicate on the "plan_type" field.
func PlanTypeEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldPlanType, v))
}

// PlanTypeNEQ applies the NEQ predicate on the "plan_type" field.
func PlanTypeNEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldPlanType, v))
}

// PlanTypeIn applies the In predicate on the "plan_type" field.
func PlanTypeIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldPlanType, vs...))
}

// PlanTypeNotIn applies the NotIn predicate on the "plan_type" field.
func PlanTypeNotIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldPlanType, vs...))
}

// PlanTypeGT applies the GT predicate on the "plan_type" field.
func PlanTypeGT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldPlanType, v))
}

// PlanTypeGTE applies the GTE predicate on the "plan_type" field.
func PlanTypeGTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldPlanType, v))
}

// PlanTypeLT applies the LT predicate on the "plan_type" field.
func PlanTypeLT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldPlanType, v))
}

// PlanTypeLTE applies the LTE predicate on the "plan_type" field.
func PlanTypeLTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldPlanType, v))
}

// PlanTypeContains applies the Contains predicate on the "plan_type" field.
func PlanTypeContains(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContains(FieldPlanType, v))
}

// PlanTypeHasPrefix applies the HasPrefix predicate on the "plan_type" field.
func PlanTypeHasPrefix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasPrefix(FieldPlanType, v))
}

// PlanTypeHasSuffix applies the HasSuffix predicate on the "plan_type" field.
func PlanTypeHasSuffix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasSuffix(FieldPlanType, v))
}

// PlanTypeIsNil applies the IsNil predicate on the "plan_type" field.
func PlanTypeIsNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIsNull(FieldPlanType))
}

// PlanTypeNotNil applies the NotNil predicate on the "plan_type" field.
func PlanTypeNotNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotNull(FieldPlanType))
}

// PlanTypeEqualFold applies the EqualFold predicate on the "plan_type" field.
func PlanTypeEqualFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEqualFold(FieldPlanType, v))
}

// PlanTypeContainsFold applies the ContainsFold predicate on the "plan_type" field.
func PlanTypeContainsFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContainsFold(FieldPlanType, v))
}

// PlanTitleEQ applies the EQ predicate on the "plan_title" field.
func PlanTitleEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldPlanTitle, v))
}

// PlanTitleNEQ applies the NEQ predicate on the "plan_title" field.
func PlanTitleNEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldPlanTitle, v))
}

// PlanTitleIn applies the In predicate on the "plan_title" field.
func PlanTitleIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldPlanTitle, vs...))
}

// PlanTitleNotIn applies the NotIn predicate on the "plan_title" field.
func PlanTitleNotIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldPlanTitle, vs...))
}

// PlanTitleGT applies the GT predicate on the "plan_title" field.
func PlanTitleGT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldPlanTitle, v))
}

// PlanTitleGTE applies the GTE predicate on the "plan_title" field.
func PlanTitleGTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldPlanTitle, v))
}

// PlanTitleLT applies the LT predicate on the "plan_title" field.
func PlanTitleLT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldPlanTitle, v))
}

// PlanTitleLTE applies the LTE predicate on the "plan_title" field.
func PlanTitleLTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldPlanTitle, v))
}

// PlanTitleContains applies the Contains predicate on the "plan_title" field.
func PlanTitleContains(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContains(FieldPlanTitle, v))
}

// PlanTitleHasPrefix applies the HasPrefix predicate on the "plan_title" field.
func PlanTitleHasPrefix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasPrefix(FieldPlanTitle, v))
}

// PlanTitleHasSuffix applies the HasSuffix predicate on the "plan_title" field.
func PlanTitleHasSuffix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasSuffix(FieldPlanTitle, v))
}

// PlanTitleIsNil applies the IsNil predicate on the "plan_title" field.
func PlanTitleIsNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIsNull(FieldPlanTitle))
}

// PlanTitleNotNil applies the NotNil predicate on the "plan_title" field.
func PlanTitleNotNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotNull(FieldPlanTitle))
}

// PlanTitleEqualFold applies the EqualFold predicate on the "plan_title" field.
func PlanTitleEqualFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEqualFold(FieldPlanTitle, v))
}

// PlanTitleContainsFold applies the ContainsFold predicate on the "plan_title" field.
func PlanTitleContainsFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContainsFold(FieldPlanTitle, v))
}

// SubscriptionEndEQ applies the EQ predicate on the "subscription_end" field.
func SubscriptionEndEQ(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldSubscriptionEnd, v))
}

// SubscriptionEndNEQ applies the NEQ predicate on the "subscription_end" field.
func SubscriptionEndNEQ(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldSubscriptionEnd, v))
}

// SubscriptionEndIn applies the In predicate on the "subscription_end" field.
func SubscriptionEndIn(vs ...time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldSubscriptionEnd, vs...))
}

// SubscriptionEndNotIn applies the NotIn predicate on the "subscription_end" field.
func SubscriptionEndNotIn(vs ...time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldSubscriptionEnd, vs...))
}

// SubscriptionEndGT applies the GT predicate on the "subscription_end" field.
func SubscriptionEndGT(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldSubscriptionEnd, v))
}

// SubscriptionEndGTE applies the GTE predicate on the "subscription_end" field.
func SubscriptionEndGTE(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldSubscriptionEnd, v))
}

// SubscriptionEndLT applies the LT predicate on the "subscription_end" field.
func SubscriptionEndLT(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldSubscriptionEnd, v))
}

// SubscriptionEndLTE applies the LTE predicate on the "subscription_end" field.
func SubscriptionEndLTE(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldSubscriptionEnd, v))
}

// SubscriptionEndIsNil applies the IsNil predicate on the "subscription_end" field.
func SubscriptionEndIsNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIsNull(FieldSubscriptionEnd))
}

// SubscriptionEndNotNil applies the NotNil predicate on the "subscription_end" field.
func SubscriptionEndNotNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotNull(FieldSubscriptionEnd))
}

// SoraSupportedEQ applies the EQ predicate on the "sora_supported" field.
func SoraSupportedEQ(v bool) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldSoraSupported, v))
}

// SoraSupportedNEQ applies the NEQ predicate on the "sora_supported" field.
func SoraSupportedNEQ(v bool) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldSoraSupported, v))
}

// SoraInviteCodeEQ applies the EQ predicate on the "sora_invite_code" field.
func SoraInviteCodeEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldSoraInviteCode, v))
}

// SoraInviteCodeNEQ applies the NEQ predicate on the "sora_invite_code" field.
func SoraInviteCodeNEQ(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldSoraInviteCode, v))
}

// SoraInviteCodeIn applies the In predicate on the "sora_invite_code" field.
func SoraInviteCodeIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldSoraInviteCode, vs...))
}

// SoraInviteCodeNotIn applies the NotIn predicate on the "sora_invite_code" field.
func SoraInviteCodeNotIn(vs ...string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldSoraInviteCode, vs...))
}

// SoraInviteCodeGT applies the GT predicate on the "sora_invite_code" field.
func SoraInviteCodeGT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldSoraInviteCode, v))
}

// SoraInviteCodeGTE applies the GTE predicate on the "sora_invite_code" field.
func SoraInviteCodeGTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldSoraInviteCode, v))
}

// SoraInviteCodeLT applies the LT predicate on the "sora_invite_code" field.
func SoraInviteCodeLT(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldSoraInviteCode, v))
}

// SoraInviteCodeLTE applies the LTE predicate on the "sora_invite_code" field.
func SoraInviteCodeLTE(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldSoraInviteCode, v))
}

// SoraInviteCodeContains applies the Contains predicate on the "sora_invite_code" field.
func SoraInviteCodeContains(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContains(FieldSoraInviteCode, v))
}

// SoraInviteCodeHasPrefix applies the HasPrefix predicate on the "sora_invite_code" field.
func SoraInviteCodeHasPrefix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasPrefix(FieldSoraInviteCode, v))
}

// SoraInviteCodeHasSuffix applies the HasSuffix predicate on the "sora_invite_code" field.
func SoraInviteCodeHasSuffix(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldHasSuffix(FieldSoraInviteCode, v))
}

// SoraInviteCodeIsNil applies the IsNil predicate on the "sora_invite_code" field.
func SoraInviteCodeIsNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIsNull(FieldSoraInviteCode))
}

// SoraInviteCodeNotNil applies the NotNil predicate on the "sora_invite_code" field.
func SoraInviteCodeNotNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotNull(FieldSoraInviteCode))
}

// SoraInviteCodeEqualFold applies the EqualFold predicate on the "sora_invite_code" field.
func SoraInviteCodeEqualFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEqualFold(FieldSoraInviteCode, v))
}

// SoraInviteCodeContainsFold applies the ContainsFold predicate on the "sora_invite_code" field.
func SoraInviteCodeContainsFold(v string) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldContainsFold(FieldSoraInviteCode, v))
}

// SoraRedeemedCountEQ applies the EQ predicate on the "sora_redeemed_count" field.
func SoraRedeemedCountEQ(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldSoraRedeemedCount, v))
}

// SoraRedeemedCountNEQ applies the NEQ predicate on the "sora_redeemed_count" field.
func SoraRedeemedCountNEQ(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldSoraRedeemedCount, v))
}

// SoraRedeemedCountIn applies the In predicate on the "sora_redeemed_count" field.
func SoraRedeemedCountIn(vs ...int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldSoraRedeemedCount, vs...))
}

// SoraRedeemedCountNotIn applies the NotIn predicate on the "sora_redeemed_count" field.
func SoraRedeemedCountNotIn(vs ...int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldSoraRedeemedCount, vs...))
}

// SoraRedeemedCountGT applies the GT predicate on the "sora_redeemed_count" field.
func SoraRedeemedCountGT(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldSoraRedeemedCount, v))
}

// SoraRedeemedCountGTE applies the GTE predicate on the "sora_redeemed_count" field.
func SoraRedeemedCountGTE(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldSoraRedeemedCount, v))
}

// SoraRedeemedCountLT applies the LT predicate on the "sora_redeemed_count" field.
func SoraRedeemedCountLT(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldSoraRedeemedCount, v))
}

// SoraRedeemedCountLTE applies the LTE predicate on the "sora_redeemed_count" field.
func SoraRedeemedCountLTE(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldSoraRedeemedCount, v))
}

// SoraRemainingCountEQ applies the EQ predicate on the "sora_remaining_count" field.
func SoraRemainingCountEQ(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldSoraRemainingCount, v))
}

// SoraRemainingCountNEQ applies the NEQ predicate on the "sora_remaining_count" field.
func SoraRemainingCountNEQ(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldSoraRemainingCount, v))
}

// SoraRemainingCountIn applies the In predicate on the "sora_remaining_count" field.
func SoraRemainingCountIn(vs ...int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldSoraRemainingCount, vs...))
}

// SoraRemainingCountNotIn applies the NotIn predicate on the "sora_remaining_count" field.
func SoraRemainingCountNotIn(vs ...int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldSoraRemainingCount, vs...))
}

// SoraRemainingCountGT applies the GT predicate on the "sora_remaining_count" field.
func SoraRemainingCountGT(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldSoraRemainingCount, v))
}

// SoraRemainingCountGTE applies the GTE predicate on the "sora_remaining_count" field.
func SoraRemainingCountGTE(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldSoraRemainingCount, v))
}

// SoraRemainingCountLT applies the LT predicate on the "sora_remaining_count" field.
func SoraRemainingCountLT(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldSoraRemainingCount, v))
}

// SoraRemainingCountLTE applies the LTE predicate on the "sora_remaining_count" field.
func SoraRemainingCountLTE(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldSoraRemainingCount, v))
}

// SoraTotalCountEQ applies the EQ predicate on the "sora_total_count" field.
func SoraTotalCountEQ(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldSoraTotalCount, v))
}

// SoraTotalCountNEQ applies the NEQ predicate on the "sora_total_count" field.
func SoraTotalCountNEQ(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldSoraTotalCount, v))
}

// SoraTotalCountIn applies the In predicate on the "sora_total_count" field.
func SoraTotalCountIn(vs ...int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldSoraTotalCount, vs...))
}

// SoraTotalCountNotIn applies the NotIn predicate on the "sora_total_count" field.
func SoraTotalCountNotIn(vs ...int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldSoraTotalCount, vs...))
}

// SoraTotalCountGT applies the GT predicate on the "sora_total_count" field.
func SoraTotalCountGT(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldSoraTotalCount, v))
}

// SoraTotalCountGTE applies the GTE predicate on the "sora_total_count" field.
func SoraTotalCountGTE(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldSoraTotalCount, v))
}

// SoraTotalCountLT applies the LT predicate on the "sora_total_count" field.
func SoraTotalCountLT(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldSoraTotalCount, v))
}

// SoraTotalCountLTE applies the LTE predicate on the "sora_total_count" field.
func SoraTotalCountLTE(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldSoraTotalCount, v))
}

// SoraCooldownUntilEQ applies the EQ predicate on the "sora_cooldown_until" field.
func SoraCooldownUntilEQ(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldSoraCooldownUntil, v))
}

// SoraCooldownUntilNEQ applies the NEQ predicate on the "sora_cooldown_until" field.
func SoraCooldownUntilNEQ(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldSoraCooldownUntil, v))
}

// SoraCooldownUntilIn applies the In predicate on the "sora_cooldown_until" field.
func SoraCooldownUntilIn(vs ...time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldSoraCooldownUntil, vs...))
}

// SoraCooldownUntilNotIn applies the NotIn predicate on the "sora_cooldown_until" field.
func SoraCooldownUntilNotIn(vs ...time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldSoraCooldownUntil, vs...))
}

// SoraCooldownUntilGT applies the GT predicate on the "sora_cooldown_until" field.
func SoraCooldownUntilGT(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldSoraCooldownUntil, v))
}

// SoraCooldownUntilGTE applies the GTE predicate on the "sora_cooldown_until" field.
func SoraCooldownUntilGTE(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldSoraCooldownUntil, v))
}

// SoraCooldownUntilLT applies the LT predicate on the "sora_cooldown_until" field.
func SoraCooldownUntilLT(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldSoraCooldownUntil, v))
}

// SoraCooldownUntilLTE applies the LTE predicate on the "sora_cooldown_until" field.
func SoraCooldownUntilLTE(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldSoraCooldownUntil, v))
}

// SoraCooldownUntilIsNil applies the IsNil predicate on the "sora_cooldown_until" field.
func SoraCooldownUntilIsNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIsNull(FieldSoraCooldownUntil))
}

// SoraCooldownUntilNotNil applies the NotNil predicate on the "sora_cooldown_until" field.
func SoraCooldownUntilNotNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotNull(FieldSoraCooldownUntil))
}

// CooledUntilEQ applies the EQ predicate on the "cooled_until" field.
func CooledUntilEQ(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldCooledUntil, v))
}

// CooledUntilNEQ applies the NEQ predicate on the "cooled_until" field.
func CooledUntilNEQ(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldCooledUntil, v))
}

// CooledUntilIn applies the In predicate on the "cooled_until" field.
func CooledUntilIn(vs ...time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldCooledUntil, vs...))
}

// CooledUntilNotIn applies the NotIn predicate on the "cooled_until" field.
func CooledUntilNotIn(vs ...time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldCooledUntil, vs...))
}

// CooledUntilGT applies the GT predicate on the "cooled_until" field.
func CooledUntilGT(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldCooledUntil, v))
}

// CooledUntilGTE applies the GTE predicate on the "cooled_until" field.
func CooledUntilGTE(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldCooledUntil, v))
}

// CooledUntilLT applies the LT predicate on the "cooled_until" field.
func CooledUntilLT(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldCooledUntil, v))
}

// CooledUntilLTE applies the LTE predicate on the "cooled_until" field.
func CooledUntilLTE(v time.Time) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldCooledUntil, v))
}

// CooledUntilIsNil applies the IsNil predicate on the "cooled_until" field.
func CooledUntilIsNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIsNull(FieldCooledUntil))
}

// CooledUntilNotNil applies the NotNil predicate on the "cooled_until" field.
func CooledUntilNotNil() predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotNull(FieldCooledUntil))
}

// ImageEnabledEQ applies the EQ predicate on the "image_enabled" field.
func ImageEnabledEQ(v bool) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldImageEnabled, v))
}

// ImageEnabledNEQ applies the NEQ predicate on the "image_enabled" field.
func ImageEnabledNEQ(v bool) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldImageEnabled, v))
}

// VideoEnabledEQ applies the EQ predicate on the "video_enabled" field.
func VideoEnabledEQ(v bool) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldVideoEnabled, v))
}

// VideoEnabledNEQ applies the NEQ predicate on the "video_enabled" field.
func VideoEnabledNEQ(v bool) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldVideoEnabled, v))
}

// ImageConcurrencyEQ applies the EQ predicate on the "image_concurrency" field.
func ImageConcurrencyEQ(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldImageConcurrency, v))
}

// ImageConcurrencyNEQ applies the NEQ predicate on the "image_concurrency" field.
func ImageConcurrencyNEQ(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldImageConcurrency, v))
}

// ImageConcurrencyIn applies the In predicate on the "image_concurrency" field.
func ImageConcurrencyIn(vs ...int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldImageConcurrency, vs...))
}

// ImageConcurrencyNotIn applies the NotIn predicate on the "image_concurrency" field.
func ImageConcurrencyNotIn(vs ...int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldImageConcurrency, vs...))
}

// ImageConcurrencyGT applies the GT predicate on the "image_concurrency" field.
func ImageConcurrencyGT(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldImageConcurrency, v))
}

// ImageConcurrencyGTE applies the GTE predicate on the "image_concurrency" field.
func ImageConcurrencyGTE(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldImageConcurrency, v))
}

// ImageConcurrencyLT applies the LT predicate on the "image_concurrency" field.
func ImageConcurrencyLT(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldImageConcurrency, v))
}

// ImageConcurrencyLTE applies the LTE predicate on the "image_concurrency" field.
func ImageConcurrencyLTE(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldImageConcurrency, v))
}

// VideoConcurrencyEQ applies the EQ predicate on the "video_concurrency" field.
func VideoConcurrencyEQ(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldVideoConcurrency, v))
}

// VideoConcurrencyNEQ applies the NEQ predicate on the "video_concurrency" field.
func VideoConcurrencyNEQ(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldVideoConcurrency, v))
}

// VideoConcurrencyIn applies the In predicate on the "video_concurrency" field.
func VideoConcurrencyIn(vs ...int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldIn(FieldVideoConcurrency, vs...))
}

// VideoConcurrencyNotIn applies the NotIn predicate on the "video_concurrency" field.
func VideoConcurrencyNotIn(vs ...int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNotIn(FieldVideoConcurrency, vs...))
}

// VideoConcurrencyGT applies the GT predicate on the "video_concurrency" field.
func VideoConcurrencyGT(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGT(FieldVideoConcurrency, v))
}

// VideoConcurrencyGTE applies the GTE predicate on the "video_concurrency" field.
func VideoConcurrencyGTE(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldGTE(FieldVideoConcurrency, v))
}

// VideoConcurrencyLT applies the LT predicate on the "video_concurrency" field.
func VideoConcurrencyLT(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLT(FieldVideoConcurrency, v))
}

// VideoConcurrencyLTE applies the LTE predicate on the "video_concurrency" field.
func VideoConcurrencyLTE(v int) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldLTE(FieldVideoConcurrency, v))
}

// IsExpiredEQ applies the EQ predicate on the "is_expired" field.
func IsExpiredEQ(v bool) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldEQ(FieldIsExpired, v))
}

// IsExpiredNEQ applies the NEQ predicate on the "is_expired" field.
func IsExpiredNEQ(v bool) predicate.SoraAccount {
	return predicate.SoraAccount(sql.FieldNEQ(FieldIsExpired, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SoraAccount) predicate.SoraAccount {
	return predicate.SoraAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SoraAccount) predicate.SoraAccount {
	return predicate.SoraAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SoraAccount) predicate.SoraAccount {
	return predicate.SoraAccount(sql.NotPredicates(p))
}
